[tool.ruff]
line-length = 100
target-version = "py313"

[lint]
select = ["E", "F", "W", "I", "UP", "B", "C4", "SIM"]
ignore = [
    "E501",   # line-length — coberta pelo formatter
    "B008",   # do not perform function call in default arguments (DRF usa isso)
]

[lint.per-file-ignores]
"*/migrations/*.py" = ["E501", "F401"]
"*/tests.py" = ["S101"]

[format]
quote-style = "double"
indent-style = "space"
