# Generated by Django 5.2.6 on 2026-05-01 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('omr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='core.classgroup', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='exam',
            name='options_count',
            field=models.PositiveIntegerField(default=5, help_text='Quantidade de alternativas por questão. Exemplo: 4 para A-D, 5 para A-E.', verbose_name='Quantidade de alternativas'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions_count',
            field=models.PositiveIntegerField(default=8, help_text='Quantidade total de questões da prova.', verbose_name='Quantidade de questões'),
        ),
        migrations.AddField(
            model_name='exam',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='exam_templates/', verbose_name='Modelo de gabarito'),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_results', to='core.student', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='answer_key',
            field=models.JSONField(blank=True, help_text="Lista de respostas corretas. Exemplo: ['A', 'B', 'C', 'D'].", null=True, verbose_name='Gabarito'),
        ),
    ]
