# Generated by Django 5.2.6 on 2026-05-02 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('omr', '0002_exam_class_group_exam_options_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='answer_key',
            field=models.JSONField(help_text="Lista de respostas corretas. Exemplo: ['A', 'B', 'C', 'D'].", verbose_name='Gabarito'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='core.classgroup', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='options_count',
            field=models.PositiveIntegerField(default=4, help_text='Quantidade de alternativas por questão. Exemplo: 4 de A-D', verbose_name='Quantidade de alternativas'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='questions_count',
            field=models.PositiveIntegerField(default=8, help_text='Quantidade total de questões da prova. Mínimo 8 e máximo 30.', verbose_name='Quantidade de questões'),
        ),
    ]
